name: Run Stocks Script and push Changes

on:
  schedule:
    # Runs daily at 10:00 AM UTC
    - cron: '0 10 * * *'
  workflow_dispatch:  # Allows manual trigger of the workflow

permissions:
  contents: write # Grant write permissions to push changes

jobs:
  run-stocks:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: true # Ensures credentials are available for pushing changes.

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install dependencies (if you have any)
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt  # Install dependencies if a requirements.txt exists
        fi
        python stocks.py  # Run the Python script

    # Step 4: Commit and push changes if there are any
    - name: Commit and push changes
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Stage all changes
        git add .

        # Commit changes if any changes exist
        git commit -m "Automated changes by stocks.py script" || echo "No changes to commit"

        # Only push if there were changes committed
        git push origin main || echo "No changes to push"

